In [ ]:
import pandas as pd
import numpy as np

## Extracting features of 2018 movies from Wikipedia

In [2]:
import pandas as pd
import numpy as np
import requests
import time
from io import StringIO

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

tables = pd.read_html(StringIO(response.text))

df1 = tables[2]
df2 = tables[3]
df3 = tables[4]
df4 = tables[5]

In [3]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [4]:
df1 = df[['Title']]

print(df1.head())

                     Title
0  Insidious: The Last Key
1         The Strange Ones
2             The Commuter
3               Proud Mary
4         Acts of Violence

In [5]:
API_KEY = "da8a88c9410d08718361982f107d161f"

tmdb_headers = {
    "User-Agent": "Mozilla/5.0"
}

In [7]:
import requests
import numpy as np
import time

API_KEY = "da8a88c9410d08718361982f107d161f"

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0",
    "Connection": "keep-alive"
})

def get_movie_genres(title):

    for attempt in range(3):

        try:

            # SEARCH MOVIE
            search_url = "https://api.themoviedb.org/3/search/movie"

            search_response = session.get(
                search_url,
                params={
                    "api_key": API_KEY,
                    "query": title
                },
                timeout=30
            )

            search_data = search_response.json()

            if len(search_data["results"]) == 0:
                return np.nan

            movie_id = search_data["results"][0]["id"]

            # MOVIE DETAILS
            details_url = f"https://api.themoviedb.org/3/movie/{movie_id}"

            details_response = session.get(
                details_url,
                params={
                    "api_key": API_KEY
                },
                timeout=30
            )

            details_data = details_response.json()

            genres = [g["name"] for g in details_data["genres"]]

            time.sleep(0)

            return " ".join(genres)

        except Exception as e:

            print(f"Retry {attempt+1} failed for {title}")

            time.sleep(5)

    return np.nan

In [8]:
df1 = df1.copy()

genres_list = []

for title in df1["Title"]:

    genres = get_movie_genres(title)

    print(title, "->", genres)

    genres_list.append(genres)

df["genres"] = genres_list

print(df)

Insidious: The Last Key -> Horror Thriller
The Strange Ones -> Drama Mystery
The Commuter -> Action Thriller Mystery
Proud Mary -> Thriller Action Crime
Acts of Violence -> Action Crime Thriller
Freak Show -> Comedy Drama
Humor Me -> Comedy
12 Strong -> War Drama Action History
Den of Thieves -> Crime Thriller Action
Forever My Girl -> Romance Drama
Thane of East County -> Drama Thriller
Maze Runner: The Death Cure -> Science Fiction Action Adventure Thriller
Please Stand By -> Comedy Drama
Winchester -> Horror Thriller
A Fantastic Woman -> Drama
Armed -> Action Comedy Crime
The Cloverfield Paradox -> Horror Mystery Science Fiction
Bad Apples -> Comedy Thriller
Peter Rabbit -> Animation Adventure Family
Pad Man -> Comedy Drama
Fifty Shades Freed -> Drama Romance
The 15:17 to Paris -> Drama Thriller
Permission -> Comedy Romance Drama
Golden Exits -> Drama
Black Panther -> Action Adventure Science Fiction
Looking Glass -> Adventure Family Fantasy
Nostalgia -> Drama Romance
Samson -> Action Drama Adventure
Game Night -> Mystery Comedy Crime
Annihilation -> Science Fiction Horror
Every Day -> Romance Fantasy
The Cured -> Horror Drama Science Fiction
Red Sparrow -> Thriller Mystery
Death Wish -> Action Crime Thriller Drama
The Vanishing of Sidney Hall -> Drama Mystery Romance
Pickings -> Thriller Action Crime Drama Mystery
A Wrinkle in Time -> Adventure Science Fiction Family Fantasy
Gringo -> Comedy Action Crime
Thoroughbreds -> Drama Thriller
The Strangers: Prey at Night -> Horror Thriller
The Hurricane Heist -> Action Adventure Crime Thriller
Tomb Raider -> Action Adventure Fantasy
Love, Simon -> Comedy Drama Romance
I Can Only Imagine -> Music Drama
Entebbe -> Thriller Drama Crime
Furlough -> Drama
Josie -> Thriller Drama
Flower -> Crime History Drama
Pacific Rim Uprising -> Action Fantasy Science Fiction Adventure
Isle of Dogs -> Adventure Comedy Animation
Sherlock Gnomes -> Animation Family Fantasy Comedy Adventure Mystery
Unsane -> Horror Thriller
Paul, Apostle of Christ -> Drama
Final Portrait -> History Drama
Midnight Sun -> Romance Drama
Ready Player One -> Adventure Action Science Fiction
Acrimony -> Drama Thriller
God's Not Dead: A Light in Darkness -> Drama
Gemini -> Science Fiction Action Adventure Thriller Drama
The Last Movie Star -> Drama
A Quiet Place -> Horror Drama Science Fiction
Blockers -> Comedy
You Were Never Really Here -> Crime Drama Thriller
Chappaquiddick -> History Drama Thriller
The Miracle Season -> Drama
Paterno -> Drama TV Movie
Beirut -> Action Thriller Drama
Rampage -> Action Adventure Science Fiction
Truth or Dare -> Thriller Horror
The Rider -> Drama Western
Sgt. Stubby: An American Hero -> Animation Adventure Family History War
Sign Gene -> Science Fiction Adventure
I Feel Pretty -> Comedy Romance
Super Troopers 2 -> Comedy Crime Mystery
Traffik -> Thriller Action
The House of Tomorrow -> Drama Comedy
Avengers: Infinity War -> Adventure Action Science Fiction
Disobedience -> Drama Romance
Backstabbing for Beginners -> Thriller Drama History
Kings -> Adventure Animation Family Fantasy
Overboard -> Romance Comedy
Tully -> Comedy Drama
Bad Samaritan -> Thriller Crime Horror Drama
The Cleanse -> Drama Comedy Fantasy Horror
RBG -> Documentary
Life of the Party -> Comedy
Breaking In -> Action Crime Thriller
The Seagull -> Drama TV Movie
Terminal -> Comedy Drama
Deadpool 2 -> Action Comedy Adventure
Show Dogs -> Adventure Crime Family Comedy
Book Club -> Romance
First Reformed -> Drama
Fahrenheit 451 -> Drama Science Fiction
Solo: A Star Wars Story -> Science Fiction Adventure Action
How to Talk to Girls at Parties -> Comedy Music Romance Science Fiction
In Darkness -> Horror Adventure
Future World -> Science Fiction
The Tale -> Fantasy Drama Adventure
Action Point -> Comedy Drama
Adrift -> Thriller Romance Adventure
Upgrade -> Action Thriller Science Fiction
American Animals -> Drama Crime Documentary
Social Animals -> Comedy Romance
Ocean's 8 -> Crime Comedy Action
Hereditary -> Horror Mystery Thriller
Hotel Artemis -> Science Fiction Crime Action Thriller Drama
Superfly -> Action Crime
Incredibles 2 -> Action Adventure Animation Family
Tag -> Comedy Action
Gotti -> Crime Drama History Thriller
Jurassic World: Fallen Kingdom -> Adventure Science Fiction Thriller
Boundaries -> Comedy Drama
Damsel -> Fantasy Action Adventure
The Domestics -> Horror Thriller
Sicario: Day of the Soldado -> Action Crime Thriller
Leave No Trace -> Drama
Love All You Have Left -> Drama
Uncle Drew -> Comedy
Woman Walks Ahead -> Drama History Western
Who's Watching Oliver -> Horror TV Movie
The First Purge -> Action Horror Thriller
Ant-Man and the Wasp -> Action Adventure Science Fiction
Sorry to Bother You -> Fantasy Science Fiction Comedy
Whitney -> Music Documentary
Hotel Transylvania 3: Summer Vacation -> Animation Comedy Family Fantasy
Skyscraper -> Action Thriller Adventure
Eighth Grade -> Comedy Drama
Don't Worry, He Won't Get Far on Foot -> Comedy Drama
Shock and Awe -> History Drama Thriller
Mamma Mia! Here We Go Again -> Comedy Romance
The Equalizer 2 -> Action Thriller Crime
Blindspotting -> Comedy Crime Drama
Unfriended: Dark Web -> Horror
Mission: Impossible – Fallout -> Action Adventure
Teen Titans Go! To the Movies -> Animation Action Comedy Science Fiction
Hot Summer Nights -> Drama Crime
Puzzle -> Horror Thriller
Extinction -> Action Drama Science Fiction Thriller
Christopher Robin -> Adventure Comedy Family Fantasy
The Darkest Minds -> Action Adventure Drama
The Spy Who Dumped Me -> Comedy Action Adventure
The Miseducation of Cameron Post -> Drama
Never Goin' Back -> Comedy
Dog Days -> Comedy Family Romance
The Meg -> Action Science Fiction Horror
BlacKkKlansman -> Crime Comedy Drama History
Slender Man -> Horror Mystery Thriller
A Prayer Before Dawn -> Drama Action Crime
Elizabeth Harvest -> Science Fiction Thriller Horror Mystery
Crazy Rich Asians -> Comedy Romance
Alpha -> Horror Drama Science Fiction
Mile 22 -> Action Thriller
The Wife -> Drama
Billionaire Boys Club -> Drama
Juliet, Naked -> Comedy Drama Romance
Down a Dark Hall -> Horror Mystery Thriller Fantasy Drama
To All the Boys I've Loved Before -> Comedy Romance
The Happytime Murders -> Action Crime Comedy
Searching -> Drama TV Movie
Papillon -> Adventure Crime Drama
A.X.L. -> Science Fiction Action Adventure Family
Operation Finale -> Drama History Thriller
Kin -> Science Fiction Action Adventure Thriller
Destination Wedding -> Romance Comedy Drama
Reprisal -> Action Adventure Thriller
The Nun -> Horror
Peppermint -> Action Thriller
The Predator -> Science Fiction Action Thriller
A Simple Favor -> Thriller Comedy Mystery
White Boy Rick -> Crime Drama
Unbroken: Path to Redemption -> Drama
The Children Act -> Drama
Lizzie -> Crime Drama Thriller
Hell House LLC II: The Abaddon Hotel -> Horror Mystery
The House with a Clock in Its Walls -> Comedy Family Fantasy Horror Mystery
Life Itself -> Drama Romance
The Sisters Brothers -> Western Drama Comedy
Assassination Nation -> Thriller Horror Comedy
Little Italy -> Comedy Romance
Colette -> Drama History
Fahrenheit 11/9 -> Documentary
Love, Gilda -> Documentary
Smallfoot -> Family Comedy Adventure Animation Fantasy
Night School -> Comedy
The Old Man & the Gun -> Comedy Crime Drama
Hell Fest -> Horror Thriller
Venom -> Science Fiction Action
A Star Is Born -> Music Drama Romance
The Great Buster: A Celebration -> Documentary Comedy
First Man -> History Drama
Bad Times at the El Royale -> Thriller Mystery Crime
Goosebumps 2: Haunted Halloween -> Comedy Fantasy Horror Family
Beautiful Boy -> Drama
The Oath -> Comedy Thriller
Gosnell: The Trial of America's Biggest Serial Killer -> Drama Crime Documentary
After Everything -> Romance Drama
Halloween -> Horror Thriller
The Hate U Give -> Crime Drama
Can You Ever Forgive Me? -> Drama Crime Comedy
Mid90s -> Drama Comedy
Wildlife -> Drama
What They Had -> Drama
My Dinner with Hervé -> Drama TV Movie
Hunter Killer -> Action Adventure Thriller
Johnny English Strikes Again -> Action Adventure Comedy
Suspiria -> Horror
Indivisible -> Drama War
Bullitt County -> Action Drama Thriller
Bohemian Rhapsody -> Music Drama
The Nutcracker and the Four Realms -> Family Fantasy Adventure
Nobody's Fool -> Drama Comedy
Boy Erased -> Drama
The Other Side of the Wind -> Drama
A Private War -> Drama War
Prospect -> Science Fiction
Bodied -> Drama Comedy Music
The Front Runner -> Drama History
The Grinch -> Animation Comedy Family Fantasy
The Girl in the Spider's Web -> Action Crime Thriller
Overlord -> Horror War Science Fiction
The Ballad of Buster Scruggs -> Western Comedy Drama
Lazer Team 2 -> Science Fiction Action Adventure Comedy
Fantastic Beasts: The Crimes of Grindelwald -> Fantasy Adventure
Widows -> Drama Crime Thriller
Green Book -> Drama Comedy History
Instant Family -> Comedy Drama
Ralph Breaks the Internet -> Action Adventure Animation Comedy Family Science Fiction
Creed II -> Drama Action
Robin Hood -> Thriller Action Drama
Roma -> Drama
The Christmas Chronicles -> Comedy Adventure Family Fantasy
The Favourite -> History Comedy Drama
Mowgli: Legend of the Jungle -> Adventure Drama
The Possession of Hannah Grace -> Horror Drama
The Cabin -> Horror Mystery Comedy
Mary Queen of Scots -> Drama History
Ben Is Back -> Drama
Spider-Man: Into the Spider-Verse -> Animation Action Adventure Science Fiction
Mortal Engines -> Adventure Science Fiction
The Mule -> Crime Drama
If Beale Street Could Talk -> Romance Drama
Mary Poppins Returns -> Fantasy Family Comedy
Aquaman -> Action Adventure Fantasy
Bumblebee -> Action Adventure Science Fiction
Welcome to Marwen -> Drama Comedy
Second Act -> Romance Comedy
Holmes & Watson -> Comedy Mystery Crime
Vice -> Drama Comedy
On the Basis of Sex -> Drama History
Destroyer -> Thriller Crime Drama Action
             Opening  Opening.1                    Title  \
0      J A N U A R Y          5  Insidious: The Last Key
1      J A N U A R Y          5         The Strange Ones
2      J A N U A R Y         12             The Commuter
3      J A N U A R Y         12               Proud Mary
4      J A N U A R Y         12         Acts of Violence
..               ...        ...                      ...
246  D E C E M B E R         21               Second Act
247  D E C E M B E R         25          Holmes & Watson
248  D E C E M B E R         25                     Vice
249  D E C E M B E R         25      On the Basis of Sex
250  D E C E M B E R         25                Destroyer

                                    Production company  \
0    Universal Pictures / Blumhouse Productions / S...
1                               Vertical Entertainment
2        Lionsgate / StudioCanal / The Picture Company
3                                          Screen Gems
4                                   Lionsgate Premiere
..                                                 ...
246                                  STX Entertainment
247  Columbia Pictures / Gary Sanchez Productions /...
248          Annapurna Pictures / Plan B Entertainment
249                                     Focus Features
250                                 Annapurna Pictures

                                         Cast and crew   Ref.  \
0    Adam Robitel (director); Leigh Whannell (scree...    [2]
1    Christopher Radcliff (director/screenplay); La...    [3]
2    Jaume Collet-Serra (director); Byron Willinger...    [4]
3    Babak Najafi (director); John S. Newman, Chris...    [5]
4    Brett Donowho (director); Nicolas Aaron Mezzan...    [6]
..                                                 ...    ...
246  Peter Segal (director); Justin Zackham, Elaine...  [238]
247  Etan Cohen (director/screenplay); Will Ferrell...  [142]
248  Adam McKay (director/screenplay); Christian Ba...  [117]
249  Mimi Leder (director); Daniel Stiepleman (scre...  [207]
250  Karyn Kusama (director); Phil Hay, Matt Manfre...  [239]

                          genres
0                Horror Thriller
1                  Drama Mystery
2        Action Thriller Mystery
3          Thriller Action Crime
4          Action Crime Thriller
..                           ...
246               Romance Comedy
247         Comedy Mystery Crime
248                 Drama Comedy
249                Drama History
250  Thriller Crime Drama Action

[251 rows x 7 columns]

In [ ]:
%pip install lxml

In [ ]:
%pip install --upgrade requests urllib3 certifi

In [9]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,genres
0,J A N U A R Y,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],Horror Thriller
1,J A N U A R Y,5,The Strange Ones,Vertical Entertainment,Christopher Radcliff (director/screenplay); La...,[3],Drama Mystery
2,J A N U A R Y,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[4],Action Thriller Mystery
3,J A N U A R Y,12,Proud Mary,Screen Gems,"Babak Najafi (director); John S. Newman, Chris...",[5],Thriller Action Crime
4,J A N U A R Y,12,Acts of Violence,Lionsgate Premiere,Brett Donowho (director); Nicolas Aaron Mezzan...,[6],Action Crime Thriller
...,...,...,...,...,...,...,...
246,D E C E M B E R,21,Second Act,STX Entertainment,"Peter Segal (director); Justin Zackham, Elaine...",[238],Romance Comedy
247,D E C E M B E R,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions /...,Etan Cohen (director/screenplay); Will Ferrell...,[142],Comedy Mystery Crime
248,D E C E M B E R,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,[117],Drama Comedy
249,D E C E M B E R,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,[207],Drama History
250,D E C E M B E R,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",[239],Thriller Crime Drama Action

In [11]:
df_2018 = df[['Title','Cast and crew','genres']]

In [12]:
df_2018["Cast and crew"][1]

'Christopher Radcliff (director/screenplay); Lauren Wolkstein (director); Alex Pettyfer, James Freedson-Jackson, Emily Althaus, Gene Jones, Owen Campbell, Tobias Campbell'

In [13]:
df_2018.head(5)

,Title,Cast and crew,genres
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Thriller
1,The Strange Ones,Christopher Radcliff (director/screenplay); La...,Drama Mystery
2,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery
3,Proud Mary,"Babak Najafi (director); John S. Newman, Chris...",Thriller Action Crime
4,Acts of Violence,Brett Donowho (director); Nicolas Aaron Mezzan...,Action Crime Thriller

In [14]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay);")[0]

In [15]:
df_2018['director_name'] = df_2018['Cast and crew'].map(lambda x: get_director(x))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7404\930721595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['director_name'] = df_2018['Cast and crew'].map(lambda x: get_director(x))

In [16]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [17]:
df_2018['actor_1_name'] = df_2018['Cast and crew'].map(lambda x: get_actor1(x))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7404\2274966287.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_1_name'] = df_2018['Cast and crew'].map(lambda x: get_actor1(x))

In [18]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1].split(", "))) <2 :
        return np.nan
    else:
         return ((x.split("screeplay); ")[-1].split(", ")[1]))

In [19]:
df_2018['actor_2_name'] = df_2018['Cast and crew'].map(lambda x: get_actor2(x))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7404\3672495884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_2_name'] = df_2018['Cast and crew'].map(lambda x: get_actor2(x))

In [20]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.nan
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [21]:
df_2018['actor_3_name'] = df_2018['Cast and crew'].map(lambda x: get_actor3(x))

In [22]:
df_2018

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,The Strange Ones,Christopher Radcliff (director/screenplay); La...,Drama Mystery,Christopher Radcliff (director/screenplay); La...,Lauren Wolkstein (director); Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,Jaume Collet-Serra,Liam Neeson,Philip de Blasi,Patrick Wilson
3,Proud Mary,"Babak Najafi (director); John S. Newman, Chris...",Thriller Action Crime,Babak Najafi,Taraji P. Henson,Christian Swegal,Billy Brown
4,Acts of Violence,Brett Donowho (director); Nicolas Aaron Mezzan...,Action Crime Thriller,Brett Donowho,Bruce Willis,Cole Hauser,Shawn Ashmore
...,...,...,...,...,...,...,...
246,Second Act,"Peter Segal (director); Justin Zackham, Elaine...",Romance Comedy,Peter Segal,Jennifer Lopez,Elaine Goldsmith-Thomas (screenplay); Jennifer...,Vanessa Hudgens
247,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Comedy Mystery Crime,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
248,Vice,Adam McKay (director/screenplay); Christian Ba...,Drama Comedy,Adam McKay,Christian Bale,Amy Adams,Steve Carell
249,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
250,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,Karyn Kusama,Nicole Kidman,Matt Manfredi (screenplay); Nicole Kidman,Toby Kebbell

In [23]:
df_2018 = df_2018.rename(columns={'Title':'movie_title'})

In [25]:
new_df18 = df_2018.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [26]:
new_df18

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Thriller,Insidious: The Last Key
1,Christopher Radcliff (director/screenplay); La...,Lauren Wolkstein (director); Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Drama Mystery,The Strange Ones
2,Jaume Collet-Serra,Liam Neeson,Philip de Blasi,Patrick Wilson,Action Thriller Mystery,The Commuter
3,Babak Najafi,Taraji P. Henson,Christian Swegal,Billy Brown,Thriller Action Crime,Proud Mary
4,Brett Donowho,Bruce Willis,Cole Hauser,Shawn Ashmore,Action Crime Thriller,Acts of Violence
...,...,...,...,...,...,...
246,Peter Segal,Jennifer Lopez,Elaine Goldsmith-Thomas (screenplay); Jennifer...,Vanessa Hudgens,Romance Comedy,Second Act
247,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Comedy Mystery Crime,Holmes & Watson
248,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Drama Comedy,Vice
249,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,On the Basis of Sex
250,Karyn Kusama,Nicole Kidman,Matt Manfredi (screenplay); Nicole Kidman,Toby Kebbell,Thriller Crime Drama Action,Destroyer

In [27]:
new_df18.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      5
actor_3_name     17
genres            0
movie_title       0
dtype: int64

In [28]:
new_df18['actor_2_name'] = new_df18['actor_2_name'].replace(np.nan, 'unknown')
new_df18['actor_3_name'] = new_df18['actor_3_name'].replace(np.nan, 'unknown')

In [29]:
new_df18['movie_title'] = new_df18['movie_title'].str.lower()

In [72]:
new_df18['comb'] = new_df18['actor_1_name'] + ' ' + new_df18['actor_2_name'] + ' '+ new_df18['actor_3_name'] + ' '+ new_df18['director_name'] +' ' + new_df18['genres']

In [73]:
new_df18

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Thriller,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Christopher Radcliff (director/screenplay); La...,Lauren Wolkstein (director); Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Drama Mystery,the strange ones,Lauren Wolkstein (director); Alex Pettyfer Jam...
2,Jaume Collet-Serra,Liam Neeson,Philip de Blasi,Patrick Wilson,Action Thriller Mystery,the commuter,Liam Neeson Philip de Blasi Patrick Wilson Jau...
3,Babak Najafi,Taraji P. Henson,Christian Swegal,Billy Brown,Thriller Action Crime,proud mary,Taraji P. Henson Christian Swegal Billy Brown ...
4,Brett Donowho,Bruce Willis,Cole Hauser,Shawn Ashmore,Action Crime Thriller,acts of violence,Bruce Willis Cole Hauser Shawn Ashmore Brett D...
...,...,...,...,...,...,...,...
246,Peter Segal,Jennifer Lopez,Elaine Goldsmith-Thomas (screenplay); Jennifer...,Vanessa Hudgens,Romance Comedy,second act,Jennifer Lopez Elaine Goldsmith-Thomas (screen...
247,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Comedy Mystery Crime,holmes & watson,Will Ferrell John C. Reilly Rebecca Hall Etan ...
248,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Drama Comedy,vice,Christian Bale Amy Adams Steve Carell Adam McK...
249,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,on the basis of sex,Felicity Jones Armie Hammer Justin Theroux Mim...
250,Karyn Kusama,Nicole Kidman,Matt Manfredi (screenplay); Nicole Kidman,Toby Kebbell,Thriller Crime Drama Action,destroyer,Nicole Kidman Matt Manfredi (screenplay); Nico...

## Extracting features of 2019 movies from Wikipedia

In [33]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
headers = {"User-Agent": "Mozilla/5.0"}
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

HTTPError: HTTP Error 403: Forbidden

In [34]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(link, headers=headers)

tables = pd.read_html(StringIO(response.text))

df1 = tables[2]
df2 = tables[3]
df3 = tables[4]
df4 = tables[5]

In [35]:
df = pd.concat([df1,df2, df3, df4], ignore_index=True)

In [36]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,4,Escape Room,Columbia Pictures / Original Film,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,J A N U A R Y,4,Rust Creek,IFC Films / Lunacy Productions,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,J A N U A R Y,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,J A N U A R Y,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,J A N U A R Y,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
247,D E C E M B E R,25,Spies in Disguise,20th Century Fox Animation / Blue Sky Studios ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[133]
248,D E C E M B E R,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[228]
249,D E C E M B E R,25,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[229]
250,D E C E M B E R,25,Just Mercy,Warner Bros. Pictures / Participant,"Destin Daniel Cretton (director/screenplay), A...",[230]
251,D E C E M B E R,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[231]

In [37]:
df['genres'] = df['Title'].map(lambda x: get_movie_genres(str(x)))

Retry 1 failed for Escape Room

In [38]:
df_2019 = df[['Title','Cast and crew','genres']]

In [39]:
df_2019

,Title,Cast and crew,genres
0,Escape Room,"Adam Robitel (director); Bragi F. Schut, Maria...",Horror Thriller Mystery
1,Rust Creek,Jen McGowan (director); Julie Lipson (screenpl...,Thriller Drama Action Crime
2,American Hangman,Wilson Coneybeare (director/screenplay); Donal...,Thriller
3,A Dog's Way Home,Charles Martin Smith (director); W. Bruce Came...,Drama Adventure Family
4,The Upside,Neil Burger (director); Jon Hartmere (screenpl...,Comedy Drama
...,...,...,...
247,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Animation Action Adventure Comedy Family
248,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama Romance
249,1917,Sam Mendes (director/screenplay); Krysty Wilso...,War History Drama
250,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama Crime History
251,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama

In [40]:
df_2019.loc[0,"Cast and crew"]

'Adam Robitel (director); Bragi F. Schut, Maria Melnik (screenplay); Taylor Russell, Logan Miller, Deborah Ann Woll, Tyler Labine, Jay Ellis, Nik Dodani, Yorick van Wageningen'

In [41]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else: 
        return x.split(" (director/screenplay)")[0]

In [42]:
df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7404\203239715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

In [43]:
def get_actor1(x):
    return ((x.split("((screenplay);)")[-1].split(", ")[0]))

In [44]:
df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7404\1562076556.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

In [45]:
def get_actor2(x):
    if len((x.split("(screenplay); ")[-1].split(", ")))<2:
        return np.nan
    else: 
        return ((x.split("(screenplay); ")[-1]).split(", ")[1])

In [46]:
df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7404\3736213850.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

In [47]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.nan
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [48]:
df_2019['actor_3_name'] = df_2019['Cast and crew'].map(lambda x: get_actor3(x))

In [49]:
df_2019 = df_2019.rename(columns={'Title':'movie_title'})

In [50]:
new_df19 = df_2019.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [51]:
new_df19['actor_2_name'] = new_df19['actor_2_name'].replace(np.nan, 'unknown')
new_df19['actor_3_name'] = new_df19['actor_3_name'].replace(np.nan, 'unknown')

In [52]:
new_df19['movie_title'] = new_df19['movie_title'].str.lower()

In [64]:
new_df19['comb'] = new_df19['actor_1_name'] + ' ' + new_df19['actor_2_name'] + ' '+ new_df19['actor_3_name'] + ' '+ new_df19['director_name'] +' ' + new_df19['genres']

In [54]:
new_df19

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Adam Robitel (director); Bragi F. Schut,Logan Miller,Deborah Ann Woll,Horror Thriller Mystery,escape room,Adam Robitel (director); Bragi F. Schut Logan ...
1,Jen McGowan,Jen McGowan (director); Julie Lipson (screenpl...,Jay Paulson,Sean O'Bryan,Thriller Drama Action Crime,rust creek,Jen McGowan (director); Julie Lipson (screenpl...
2,Wilson Coneybeare,Wilson Coneybeare (director/screenplay); Donal...,Vincent Kartheiser,Oliver Dennis,Thriller,american hangman,Wilson Coneybeare (director/screenplay); Donal...
3,Charles Martin Smith,Charles Martin Smith (director); W. Bruce Came...,Edward James Olmos,Alexandra Shipp,Drama Adventure Family,a dog's way home,Charles Martin Smith (director); W. Bruce Came...
4,Neil Burger,Neil Burger (director); Jon Hartmere (screenpl...,Kevin Hart,Nicole Kidman,Comedy Drama,the upside,Neil Burger (director); Jon Hartmere (screenpl...
...,...,...,...,...,...,...,...
247,"Nick Bruno, Troy Quane",Nick Bruno,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Nick Bruno Tom Holland Rashida Jones Nick Brun...
248,Greta Gerwig,Greta Gerwig (director/screenplay); Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Greta Gerwig (director/screenplay); Saoirse Ro...
249,Sam Mendes,Sam Mendes (director/screenplay); Krysty Wilso...,Dean-Charles Chapman,Mark Strong,War History Drama,1917,Sam Mendes (director/screenplay); Krysty Wilso...
250,Destin Daniel Cretton,Destin Daniel Cretton (director/screenplay),Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Destin Daniel Cretton (director/screenplay) Ja...
251,Chinonye Chukwu,Chinonye Chukwu (director/screenplay); Alfre W...,Wendell Pierce,Aldis Hodge,Drama,clemency,Chinonye Chukwu (director/screenplay); Alfre W...

In [65]:
my_df = pd.concat([new_df18, new_df19], ignore_index=True)

In [74]:
my_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [67]:
old_df = pd.read_csv('new_data.csv')

In [68]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,NaN
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,NaN
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,NaN
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,NaN
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,NaN
...,...,...,...,...,...,...,...
5359,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5360,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5361,Hannaleena Hauru,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mäntyvaara,Inka Haapamäki Rosa Honkonen Tiitus Rantala Ha...
5362,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5363,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [60]:
final_df = old_df.append(my_df,ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [75]:
final_df = pd.concat([old_df, my_df], ignore_index=True)

In [76]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,NaN
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,NaN
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,NaN
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,NaN
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,NaN
...,...,...,...,...,...,...,...
5862,"Nick Bruno, Troy Quane",Nick Bruno,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Nick Bruno Tom Holland Rashida Jones Nick Brun...
5863,Greta Gerwig,Greta Gerwig (director/screenplay); Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Greta Gerwig (director/screenplay); Saoirse Ro...
5864,Sam Mendes,Sam Mendes (director/screenplay); Krysty Wilso...,Dean-Charles Chapman,Mark Strong,War History Drama,1917,Sam Mendes (director/screenplay); Krysty Wilso...
5865,Destin Daniel Cretton,Destin Daniel Cretton (director/screenplay),Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Destin Daniel Cretton (director/screenplay) Ja...
5866,Chinonye Chukwu,Chinonye Chukwu (director/screenplay); Alfre W...,Wendell Pierce,Aldis Hodge,Drama,clemency,Chinonye Chukwu (director/screenplay); Alfre W...

In [77]:
final_df.isna().sum()

director_name       0
actor_1_name        0
actor_2_name        0
actor_3_name        0
genres              0
movie_title         0
comb             4906
dtype: int64

In [78]:
final_df = final_df.dropna(how='any')

In [79]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [81]:
final_df.to_csv('final_data.csv',index=False)